baseURL = "/"
languageCode = "en-us"
title = "Sumit Singh"
pygmentsUseClasses = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"

[[menu.main]]
name = "Portfolio"
url = "/portfolio/"
weight = 1
[menu.main.params]
    style = "critical"

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2
[menu.main.params]
    style = "warning"
