name: Send a toot to Mastodon when you post a new blog post

on: [pull_request]

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install requests

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 15

    - name: Post to Mastodon
      uses: sumit4613/post-to-mastodon@master
      if: "contains(github.event.head_commit.message, 'publish')"
      with:
        message: "Hello, folks! I just posted a new blog post. Check it out!"
        base-blog-url: "https://sumit4613.github.io/posts/"
        access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
        host: "fosstodon.org"
        port: "443"
        api: "api/v1"